method Main()
  decreases *
{
	{var v := decode_cyclic("uzfplzjfzcltmdly"); expect v == "fuzzplzjftcllmdy", "test 0 failed";}
	{var v := decode_cyclic("nzyegaghrzqwrdzxckn"); expect v == "ynzaegrghwzqzrdkxcn", "test 1 failed";}
	{var v := decode_cyclic("zxolecqvzyausohgzdod"); expect v == "ozxclezqvuyahsodgzod", "test 2 failed";}
	{var v := decode_cyclic("cjhzuelsabstpbq"); expect v == "hcjezualstbsqpb", "test 3 failed";}
	{var v := decode_cyclic("lfgmjpqnvzwvbusr"); expect v == "glfpmjvqnvzwsbur", "test 4 failed";}
	{var v := decode_cyclic("cvxcvhmtgbeweum"); expect v == "xcvhcvgmtwbemeu", "test 5 failed";}
	{var v := decode_cyclic("jgjvebqagrtwheytsyff"); expect v == "jjgbvegqawrtyheytsff", "test 6 failed";}
	{var v := decode_cyclic("swbkfgqnvuahcnqgpcu"); expect v == "bswgkfvqnhuaqcncgpu", "test 7 failed";}
	{var v := decode_cyclic("ssjgajmprs"); expect v == "jssjgarmps", "test 8 failed";}
	{var v := decode_cyclic("enrrdusnffcnkotf"); expect v == "renurdfsnnfctkof", "test 9 failed";}
	{var v := decode_cyclic("cpfgdusjrzf"); expect v == "fcpugdrsjzf", "test 10 failed";}
	{var v := decode_cyclic("gconqokfgb"); expect v == "ogconqgkfb", "test 11 failed";}
	{var v := decode_cyclic("effmnsvrgsdbhffn"); expect v == "fefsmngvrbsdfhfn", "test 12 failed";}
	{var v := decode_cyclic("zwsrgynxlmh"); expect v == "szwyrglnxmh", "test 13 failed";}
	{var v := decode_cyclic("nqdjadvhlu"); expect v == "dnqdjalvhu", "test 14 failed";}
	{var v := decode_cyclic("fpkocdqllglypkj"); expect v == "kfpdoclqlygljpk", "test 15 failed";}
	{var v := decode_cyclic("aosjbowaac"); expect v == "saoojbawac", "test 16 failed";}
	{var v := decode_cyclic("fvdumeezuebnlkqnvwfc"); expect v == "dfveumueznebqlkwnvfc", "test 17 failed";}
	{var v := decode_cyclic("tzfoanbvufs"); expect v == "ftznoaubvfs", "test 18 failed";}
	{var v := decode_cyclic("mnzbtfatwfxpqstecjm"); expect v == "zmnfbtwatpfxtqsjecm", "test 19 failed";}
	{var v := decode_cyclic("nkxxaitehrj"); expect v == "xnkixahterj", "test 20 failed";}
	{var v := decode_cyclic("nwxwbyaavoevbjbig"); expect v == "xnwywbvaavoebbjig", "test 21 failed";}
	{var v := decode_cyclic("gmamklorekv"); expect v == "agmlmkeorkv", "test 22 failed";}
	{var v := decode_cyclic("rihdqvrbxaycb"); expect v == "hrivdqxrbcayb", "test 23 failed";}
	{var v := decode_cyclic("gwvexchafqe"); expect v == "vgwcexfhaqe", "test 24 failed";}
	{var v := decode_cyclic("pymjpgzjnva"); expect v == "mpygjpnzjva", "test 25 failed";}
	{var v := decode_cyclic("aobgbpwjritkq"); expect v == "baopgbrwjkitq", "test 26 failed";}
	{var v := decode_cyclic("nuccsadagbriq"); expect v == "cnuacsgdaibrq", "test 27 failed";}
	{var v := decode_cyclic("gdktamtzhdmj"); expect v == "kgdmtahtzjdm", "test 28 failed";}
	{var v := decode_cyclic("dcprihgimgnjx"); expect v == "pdchrimgijgnx", "test 29 failed";}
	{var v := decode_cyclic("kljtwssfqty"); expect v == "jklstwqsfty", "test 30 failed";}
	{var v := decode_cyclic("frbqiejenuvxwoy"); expect v == "bfreqinjexuvywo", "test 31 failed";}
	{var v := decode_cyclic("tjfuyuhxly"); expect v == "ftjuuylhxy", "test 32 failed";}
	{var v := decode_cyclic("fimmmlfohx"); expect v == "mfilmmhfox", "test 33 failed";}
	{var v := decode_cyclic("xwtgrxfyytcyyjdjoni"); expect v == "txwxgryfyytcdyjnjoi", "test 34 failed";}
	{var v := decode_cyclic("bzekhcvbldsd"); expect v == "ebzckhlvbdds", "test 35 failed";}
	{var v := decode_cyclic("ghzgwvsorsye"); expect v == "zghvgwrsoesy", "test 36 failed";}
	{var v := decode_cyclic("xkaxuitdibnplwpucw"); expect v == "axkixuitdpbnplwwuc", "test 37 failed";}
	{var v := decode_cyclic("qcszxfbaocdzseekb"); expect v == "sqcfzxobazcdesekb", "test 38 failed";}
	{var v := decode_cyclic("ueaztzzgmex"); expect v == "auezztmzgex", "test 39 failed";}
	{var v := decode_cyclic("jsjyrkasqpujtnvrbmtr"); expect v == "jjskyrqasjpuvtnmrbtr", "test 40 failed";}
	{var v := decode_cyclic("fyiurdclyxoalovncksg"); expect v == "ifyduryclaxovlokncsg", "test 41 failed";}
	{var v := decode_cyclic("erxobpjrpkxbsgobas"); expect v == "xerpobpjrbkxosgsba", "test 42 failed";}
	{var v := decode_cyclic("lizudkhwdzwjzziyex"); expect v == "zlikuddhwjzwizzxye", "test 43 failed";}
	{var v := decode_cyclic("vpuzbwgjyicrh"); expect v == "uvpwzbygjrich", "test 44 failed";}
	{var v := decode_cyclic("sajlxmochmknulkxecik"); expect v == "jsamlxhocnmkkulcxeik", "test 45 failed";}
	{var v := decode_cyclic("klzoujwdjfwqzk"); expect v == "zkljoujwdqfwzk", "test 46 failed";}
	{var v := decode_cyclic("kiccixaihigbhftw"); expect v == "ckixcihaibigthfw", "test 47 failed";}
	{var v := decode_cyclic("hyrkynsmkvndymdepsu"); expect v == "rhynkyksmdvndymsepu", "test 48 failed";}
	{var v := decode_cyclic("dplbtwiqweagdz"); expect v == "ldpwbtwiqgeadz", "test 49 failed";}
	{var v := decode_cyclic("kjrblffzlakwpz"); expect v == "rkjfbllfzwakpz", "test 50 failed";}
	{var v := decode_cyclic("hzdeezpqcoxwcwsyyl"); expect v == "dhzzeecpqwoxscwlyy", "test 51 failed";}
	{var v := decode_cyclic("wcxtvtdgeymblafldwgq"); expect v == "xwcttvedgbymflawldgq", "test 52 failed";}
	{var v := decode_cyclic("ujgibazfslkfyfu"); expect v == "gujaibszfflkuyf", "test 53 failed";}
	{var v := decode_cyclic("oqrngzmyfxddlwpbv"); expect v == "roqzngfmydxdplwbv", "test 54 failed";}
	{var v := decode_cyclic("vtmdwyiilv"); expect v == "mvtydwliiv", "test 55 failed";}
	{var v := decode_cyclic("vghazccwxyibefx"); expect v == "hvgcazxcwbyixef", "test 56 failed";}
	{var v := decode_cyclic("jzyhtisowtzheniomrvr"); expect v == "yjzihtwsohtzienromvr", "test 57 failed";}
	{var v := decode_cyclic("eksylebplf"); expect v == "sekeyllbpf", "test 58 failed";}
	{var v := decode_cyclic("jxevtanxqvhwb"); expect v == "ejxavtqnxwvhb", "test 59 failed";}
	{var v := decode_cyclic("joqwqljwckpb"); expect v == "qjolwqcjwbkp", "test 60 failed";}
	{var v := decode_cyclic("dkghzktgig"); expect v == "gdkkhzitgg", "test 61 failed";}
	{var v := decode_cyclic("ajbtmlaqsegfktujz"); expect v == "bajltmsaqfeguktjz", "test 62 failed";}
	{var v := decode_cyclic("xeggrighqjvgjpt"); expect v == "gxeigrqghgjvtjp", "test 63 failed";}
	{var v := decode_cyclic("fgkpcfreaypwkstc"); expect v == "kfgfpcarewyptksc", "test 64 failed";}
	{var v := decode_cyclic("ucfyampthmhoh"); expect v == "fucmyahptomhh", "test 65 failed";}
	{var v := decode_cyclic("pcyzbxlzmud"); expect v == "ypcxzbmlzud", "test 66 failed";}
	{var v := decode_cyclic("hualgpgmtpv"); expect v == "ahuplgtgmpv", "test 67 failed";}
	{var v := decode_cyclic("dofgkmknkdhimryg"); expect v == "fdomgkkknidhymrg", "test 68 failed";}
	{var v := decode_cyclic("btvvhktzpvkuekialfq"); expect v == "vbtkvhptzuvkiekfalq", "test 69 failed";}
	{var v := decode_cyclic("hbvgnvmuxckcqjvx"); expect v == "vhbvgnxmucckvqjx", "test 70 failed";}
	{var v := decode_cyclic("qhwrawfsmuevokszgfqy"); expect v == "wqhwramfsvuesokfzgqy", "test 71 failed";}
	{var v := decode_cyclic("uakqzvnihhfcwz"); expect v == "kuavqzhnichfwz", "test 72 failed";}
	{var v := decode_cyclic("rlnvwwhoxlwkyibhnjg"); expect v == "nrlwvwxhoklwbyijhng", "test 73 failed";}
	{var v := decode_cyclic("cmprarjwtqovlcizhgpu"); expect v == "pcmrratjwvqoilcgzhpu", "test 74 failed";}
	{var v := decode_cyclic("rbfrlfpxzfm"); expect v == "frbfrlzpxfm", "test 75 failed";}
	{var v := decode_cyclic("lutbkxocedmbfctzmuy"); expect v == "tluxbkeocbdmtfcuzmy", "test 76 failed";}
	{var v := decode_cyclic("oajodvoerl"); expect v == "joavodroel", "test 77 failed";}
	{var v := decode_cyclic("bvmxponldendphf"); expect v == "mbvoxpdnldenfph", "test 78 failed";}
	{var v := decode_cyclic("jdliznkftyvzwdqty"); expect v == "ljdniztkfzyvqwdty", "test 79 failed";}
	{var v := decode_cyclic("hkbaihpjquf"); expect v == "bhkhaiqpjuf", "test 80 failed";}
	{var v := decode_cyclic("hhneeogusm"); expect v == "nhhoeesgum", "test 81 failed";}
	{var v := decode_cyclic("qvnehikoshpzahmfkep"); expect v == "nqviehskozhpmahefkp", "test 82 failed";}
	{var v := decode_cyclic("urrclsjxeosc"); expect v == "rursclejxcos", "test 83 failed";}
	{var v := decode_cyclic("ghfmyzjawzulrop"); expect v == "fghzmywjalzupro", "test 84 failed";}
	{var v := decode_cyclic("ycqtsqaatceckf"); expect v == "qycqtstaaccekf", "test 85 failed";}
	{var v := decode_cyclic("ipybztxdkypoxjuhf"); expect v == "yiptbzkxdoypuxjhf", "test 86 failed";}
	{var v := decode_cyclic("ozjthdoukvrqjb"); expect v == "jozdthkouqvrjb", "test 87 failed";}
	{var v := decode_cyclic("ipfbolvlrwwtznrdbta"); expect v == "fiplborvltwwrzntdba", "test 88 failed";}
	{var v := decode_cyclic("xzhjnclgnihoinfs"); expect v == "hxzcjnnlgoihfins", "test 89 failed";}
	{var v := decode_cyclic("pfkwcebjnkoudgosogtj"); expect v == "kpfewcnbjukoodggsotj", "test 90 failed";}
	{var v := decode_cyclic("aqbojzzuehqwirlx"); expect v == "baqzojezuwhqlirx", "test 91 failed";}
	{var v := decode_cyclic("mulyzumnbuzr"); expect v == "lmuuyzbmnruz", "test 92 failed";}
	{var v := decode_cyclic("nzdtnhuxogdzdguy"); expect v == "dnzhtnouxzgdudgy", "test 93 failed";}
	{var v := decode_cyclic("juvowhyjstne"); expect v == "vjuhowsyjetn", "test 94 failed";}
	{var v := decode_cyclic("ybzdvuvvwyeyxepv"); expect v == "zybudvwvvyyepxev", "test 95 failed";}
	{var v := decode_cyclic("dyunpcsjbdozu"); expect v == "udycnpbsjzdou", "test 96 failed";}
	{var v := decode_cyclic("hfbhubqoykkyrwjx"); expect v == "bhfbhuyqoykkjrwx", "test 97 failed";}
	{var v := decode_cyclic("bkkjxpyfzrtcqpqna"); expect v == "kbkpjxzyfcrtqqpna", "test 98 failed";}
	{var v := decode_cyclic("hpncxsmjpus"); expect v == "nhpscxpmjus", "test 99 failed";}
}