method Main()
  decreases *
{
	{var v := decode_shift("tantywccpjkimslotpzs"); expect v == "oviotrxxkefdhngjokun", "test 0 failed";}
	{var v := decode_shift("clknfxdnox"); expect v == "xgfiasyijs", "test 1 failed";}
	{var v := decode_shift("dtzqyosaovdbafbg"); expect v == "youltjnvjqywvawb", "test 2 failed";}
	{var v := decode_shift("dffjvztknohzf"); expect v == "yaaequofijcua", "test 3 failed";}
	{var v := decode_shift("brhkdngfwd"); expect v == "wmcfyibary", "test 4 failed";}
	{var v := decode_shift("amlcrporykmgbhzctpnh"); expect v == "vhgxmkjmtfhbwcuxokic", "test 5 failed";}
	{var v := decode_shift("ondbgojmipwoofzeyrh"); expect v == "jiywbjehdkrjjauztmc", "test 6 failed";}
	{var v := decode_shift("atobiwyiitrvhuctz"); expect v == "vojwdrtddomqcpxou", "test 7 failed";}
	{var v := decode_shift("kyrzjawonglfbsedmhmk"); expect v == "ftmuevrjibgawnzyhchf", "test 8 failed";}
	{var v := decode_shift("esusgpgnaelf"); expect v == "znpnbkbivzga", "test 9 failed";}
	{var v := decode_shift("jbocbcqiuggvenbq"); expect v == "ewjxwxldpbbqziwl", "test 10 failed";}
	{var v := decode_shift("zmmcumljlx"); expect v == "uhhxphgegs", "test 11 failed";}
	{var v := decode_shift("ibrcruwukgetv"); expect v == "dwmxmprpfbzoq", "test 12 failed";}
	{var v := decode_shift("ncbelcfjqcgxshtdiz"); expect v == "ixwzgxaelxbsncoydu", "test 13 failed";}
	{var v := decode_shift("xgcckzjdfp"); expect v == "sbxxfueyak", "test 14 failed";}
	{var v := decode_shift("gzlnmjjytxhydvy"); expect v == "bugiheetosctyqt", "test 15 failed";}
	{var v := decode_shift("zxlxfflljav"); expect v == "usgsaaggevq", "test 16 failed";}
	{var v := decode_shift("kfeabaemohxvodorv"); expect v == "fazvwvzhjcsqjyjmq", "test 17 failed";}
	{var v := decode_shift("kdfcevzlswkkmkwdrcrg"); expect v == "fyaxzqugnrffhfrymxmb", "test 18 failed";}
	{var v := decode_shift("oxtrmhyjjbm"); expect v == "jsomhcteewh", "test 19 failed";}
	{var v := decode_shift("bvhfetbvrspmepdqu"); expect v == "wqcazowqmnkhzkylp", "test 20 failed";}
	{var v := decode_shift("lycqknawupoydpve"); expect v == "gtxlfivrpkjtykqz", "test 21 failed";}
	{var v := decode_shift("vmbjsfxvtgjkxgvazub"); expect v == "qhwenasqobefsbqvupw", "test 22 failed";}
	{var v := decode_shift("ffkskhcrjnixkkdivamc"); expect v == "aafnfcxmeidsffydqvhx", "test 23 failed";}
	{var v := decode_shift("zszowxcyfksyaiov"); expect v == "unujrsxtafntvdjq", "test 24 failed";}
	{var v := decode_shift("mcqqnjopwar"); expect v == "hxlliejkrvm", "test 25 failed";}
	{var v := decode_shift("dkglzmaccvjlrjuhgmp"); expect v == "yfbguhvxxqegmepcbhk", "test 26 failed";}
	{var v := decode_shift("hudnjifakmaknaiwjjoz"); expect v == "cpyiedavfhvfivdreeju", "test 27 failed";}
	{var v := decode_shift("ppineedncm"); expect v == "kkdizzyixh", "test 28 failed";}
	{var v := decode_shift("nhnnpeyazv"); expect v == "iciikztvuq", "test 29 failed";}
	{var v := decode_shift("hfgrlomgpnzomltm"); expect v == "cabmgjhbkiujhgoh", "test 30 failed";}
	{var v := decode_shift("opejcxrnkfi"); expect v == "jkzexsmifad", "test 31 failed";}
	{var v := decode_shift("caocjafernbzwkerkjul"); expect v == "xvjxevazmiwurfzmfepg", "test 32 failed";}
	{var v := decode_shift("uenrgscamkc"); expect v == "pzimbnxvhfx", "test 33 failed";}
	{var v := decode_shift("ntphbmfuyhgxxekrh"); expect v == "iokcwhaptcbsszfmc", "test 34 failed";}
	{var v := decode_shift("lullbgnzzlpsf"); expect v == "gpggwbiuugkna", "test 35 failed";}
	{var v := decode_shift("nfzgyzvqkkkhqwoc"); expect v == "iaubtuqlfffclrjx", "test 36 failed";}
	{var v := decode_shift("rseeagndpy"); expect v == "mnzzvbiykt", "test 37 failed";}
	{var v := decode_shift("jzfmflvqsujn"); expect v == "euahagqlnpei", "test 38 failed";}
	{var v := decode_shift("zhemzjdbgmzhlojon"); expect v == "uczhueywbhucgjeji", "test 39 failed";}
	{var v := decode_shift("bejmmyaivqmztwx"); expect v == "wzehhtvdqlhuors", "test 40 failed";}
	{var v := decode_shift("dkrixwritnwanp"); expect v == "yfmdsrmdoirvik", "test 41 failed";}
	{var v := decode_shift("phbenxhnsrceqgo"); expect v == "kcwziscinmxzlbj", "test 42 failed";}
	{var v := decode_shift("lkwatqvqox"); expect v == "gfrvolqljs", "test 43 failed";}
	{var v := decode_shift("sodavpratfhciez"); expect v == "njyvqkmvoacxdzu", "test 44 failed";}
	{var v := decode_shift("rdbebqamnqnrojlyc"); expect v == "mywzwlvhilimjegtx", "test 45 failed";}
	{var v := decode_shift("qpcjvbttxkfoarmbgaj"); expect v == "lkxeqwoosfajvmhwbve", "test 46 failed";}
	{var v := decode_shift("buoybjwmnkca"); expect v == "wpjtwerhifxv", "test 47 failed";}
	{var v := decode_shift("zhsxvqgydfzom"); expect v == "ucnsqlbtyaujh", "test 48 failed";}
	{var v := decode_shift("ebqzwqwgczokyqlleqv"); expect v == "zwlurlrbxujftlggzlq", "test 49 failed";}
	{var v := decode_shift("zkblrdvzwzfcucl"); expect v == "ufwgmyquruaxpxg", "test 50 failed";}
	{var v := decode_shift("qhyokykhohqmbg"); expect v == "lctjftfcjclhwb", "test 51 failed";}
	{var v := decode_shift("ppivcuwwha"); expect v == "kkdqxprrcv", "test 52 failed";}
	{var v := decode_shift("tojlipluqsrqxmkl"); expect v == "ojegdkgplnmlshfg", "test 53 failed";}
	{var v := decode_shift("pmtxclojrsx"); expect v == "khosxgjemns", "test 54 failed";}
	{var v := decode_shift("ankmnlxytriytxuycfar"); expect v == "vifhigstomdtosptxavm", "test 55 failed";}
	{var v := decode_shift("vbxyasxabsgmm"); expect v == "qwstvnsvwnbhh", "test 56 failed";}
	{var v := decode_shift("nvscnydxnomkbhzo"); expect v == "iqnxitysijhfwcuj", "test 57 failed";}
	{var v := decode_shift("qnfhjywwxbewrtwqz"); expect v == "liacetrrswzrmorlu", "test 58 failed";}
	{var v := decode_shift("qcopkrvocdnbvok"); expect v == "lxjkfmqjxyiwqjf", "test 59 failed";}
	{var v := decode_shift("vmiimkfgpijybehf"); expect v == "qhddhfabkdetwzca", "test 60 failed";}
	{var v := decode_shift("umivhawwroqbi"); expect v == "phdqcvrrmjlwd", "test 61 failed";}
	{var v := decode_shift("ngtcnxdbfem"); expect v == "iboxisywazh", "test 62 failed";}
	{var v := decode_shift("rceydgerfqlcdjwqufp"); expect v == "mxztybzmalgxyerlpak", "test 63 failed";}
	{var v := decode_shift("xiwqysuzxhrok"); expect v == "sdrltnpuscmjf", "test 64 failed";}
	{var v := decode_shift("pbiutcflmhcatu"); expect v == "kwdpoxaghcxvop", "test 65 failed";}
	{var v := decode_shift("eigoipkfsygpkzdbfba"); expect v == "zdbjdkfantbkfuywawv", "test 66 failed";}
	{var v := decode_shift("pksrbhoobdcxuzztpry"); expect v == "kfnmwcjjwyxspuuokmt", "test 67 failed";}
	{var v := decode_shift("ufpgxygqut"); expect v == "pakbstblpo", "test 68 failed";}
	{var v := decode_shift("ruysajspjftawat"); expect v == "mptnvenkeaovrvo", "test 69 failed";}
	{var v := decode_shift("htltipbsjyeyd"); expect v == "cogodkwnetzty", "test 70 failed";}
	{var v := decode_shift("nbdcbfdwridowau"); expect v == "iwyxwayrmdyjrvp", "test 71 failed";}
	{var v := decode_shift("tmppfczqbbymxz"); expect v == "ohkkaxulwwthsu", "test 72 failed";}
	{var v := decode_shift("uozrdjywqt"); expect v == "pjumyetrlo", "test 73 failed";}
	{var v := decode_shift("hntgkfcaqplmvwigugcn"); expect v == "ciobfaxvlkghqrdbpbxi", "test 74 failed";}
	{var v := decode_shift("fjvtaauddtbfxyx"); expect v == "aeqovvpyyowasts", "test 75 failed";}
	{var v := decode_shift("oueajaaouchg"); expect v == "jpzvevvjpxcb", "test 76 failed";}
	{var v := decode_shift("xjnoxinpwjxfkdhypha"); expect v == "seijsdikresafyctkcv", "test 77 failed";}
	{var v := decode_shift("ydkfspcqqgoy"); expect v == "tyfankxllbjt", "test 78 failed";}
	{var v := decode_shift("zkhvcaficnsrpftfyacc"); expect v == "ufcqxvadxinmkaoatvxx", "test 79 failed";}
	{var v := decode_shift("uhvwguwpwp"); expect v == "pcqrbprkrk", "test 80 failed";}
	{var v := decode_shift("caqjqcvjknjpxvsh"); expect v == "xvlelxqefieksqnc", "test 81 failed";}
	{var v := decode_shift("jgartypykutysuu"); expect v == "ebvmotktfpotnpp", "test 82 failed";}
	{var v := decode_shift("kcjkljbqqqllnvvn"); expect v == "fxefgewlllggiqqi", "test 83 failed";}
	{var v := decode_shift("cyhmtsgqyz"); expect v == "xtchonbltu", "test 84 failed";}
	{var v := decode_shift("kfznlgufze"); expect v == "fauigbpauz", "test 85 failed";}
	{var v := decode_shift("evvyotysuo"); expect v == "zqqtjotnpj", "test 86 failed";}
	{var v := decode_shift("bszxdxfofeuqowuul"); expect v == "wnusysajazpljrppg", "test 87 failed";}
	{var v := decode_shift("fxrorccues"); expect v == "asmjmxxpzn", "test 88 failed";}
	{var v := decode_shift("fjbitcryrirgche"); expect v == "aewdoxmtmdmbxcz", "test 89 failed";}
	{var v := decode_shift("esmaafzdoathkfbr"); expect v == "znhvvauyjvocfawm", "test 90 failed";}
	{var v := decode_shift("nyglikurdgsrxppfaaaq"); expect v == "itbgdfpmybnmskkavvvl", "test 91 failed";}
	{var v := decode_shift("tbnxtryklhivaozovo"); expect v == "owisomtfgcdqvjujqj", "test 92 failed";}
	{var v := decode_shift("ysapkxzhoyt"); expect v == "tnvkfsucjto", "test 93 failed";}
	{var v := decode_shift("szmyeptvbecdu"); expect v == "nuhtzkoqwzxyp", "test 94 failed";}
	{var v := decode_shift("aehjjihebqyikhgbfdv"); expect v == "vzceedczwltdfcbwayq", "test 95 failed";}
	{var v := decode_shift("blxkxtkcpajpuyghrj"); expect v == "wgsfsofxkvekptbcme", "test 96 failed";}
	{var v := decode_shift("yfctlzlvmg"); expect v == "taxogugqhb", "test 97 failed";}
	{var v := decode_shift("ltlczacgtm"); expect v == "gogxuvxboh", "test 98 failed";}
	{var v := decode_shift("kenorgfepxvymu"); expect v == "fzijmbazksqthp", "test 99 failed";}
}