name: Test All Dafny Files

on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Test if all dafny files are named correctly
        run: nix run .#dafny-namecheck
      - name: Run Dafny on all files
        run: nix run .#dafny-check
