name: Test All Dafny Files

on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Run Dafny Tests
        run: nix shell nixpkgs#dafny -c "scripts/dafny-test-all.sh"
